
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class ArticleItem extends ContentItem {
    public metadataOgDescription?: Elements.TextElement;
    public metadataMetaTitle?: Elements.TextElement;
    public personas?: Elements.TaxonomyElement;
    public bodyCopy?: Elements.RichTextElement;
    public metadataOgTitle?: Elements.TextElement;
    public metadataMetaDescription?: Elements.TextElement;
    public metadataTwitterSite?: Elements.TextElement;
    public postDate?: Elements.DateTimeElement;
    public metaKeywords?: Elements.TextElement;
    public teaserImage?: Elements.AssetsElement;
    public metadataTwitterImage?: Elements.AssetsElement;
    public metadataTwitterCreator?: Elements.TextElement;
    public title?: Elements.TextElement;
    public summary?: Elements.TextElement;
    public sitemap?: Elements.TaxonomyElement;
    public metadataTwitterTitle?: Elements.TextElement;
    public metadataTwitterDescription?: Elements.TextElement;
    public metaDescription?: Elements.TextElement;
    public metadataOgImage?: Elements.AssetsElement;
    public relatedArticles?: Elements.LinkedItemsElement<ContentItem>;
    public urlPattern?: Elements.UrlSlugElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__og_description') {
                    return 'metadataOgDescription';
                }
                if (elementName === 'metadata__meta_title') {
                    return 'metadataMetaTitle';
                }
                if (elementName === 'body_copy') {
                    return 'bodyCopy';
                }
                if (elementName === 'metadata__og_title') {
                    return 'metadataOgTitle';
                }
                if (elementName === 'metadata__meta_description') {
                    return 'metadataMetaDescription';
                }
                if (elementName === 'metadata__twitter_site') {
                    return 'metadataTwitterSite';
                }
                if (elementName === 'post_date') {
                    return 'postDate';
                }
                if (elementName === 'meta_keywords') {
                    return 'metaKeywords';
                }
                if (elementName === 'teaser_image') {
                    return 'teaserImage';
                }
                if (elementName === 'metadata__twitter_image') {
                    return 'metadataTwitterImage';
                }
                if (elementName === 'metadata__twitter_creator') {
                    return 'metadataTwitterCreator';
                }
                if (elementName === 'metadata__twitter_title') {
                    return 'metadataTwitterTitle';
                }
                if (elementName === 'metadata__twitter_description') {
                    return 'metadataTwitterDescription';
                }
                if (elementName === 'meta_description') {
                    return 'metaDescription';
                }
                if (elementName === 'metadata__og_image') {
                    return 'metadataOgImage';
                }
                if (elementName === 'related_articles') {
                    return 'relatedArticles';
                }
                if (elementName === 'url_pattern') {
                    return 'urlPattern';
                }
                return elementName;
            })
        });
    }
}
