
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class CafeItem extends ContentItem {
    public phone?: Elements.TextElement;
    public city?: Elements.TextElement;
    public photo?: Elements.AssetsElement;
    public email?: Elements.TextElement;
    public country?: Elements.TextElement;
    public street?: Elements.TextElement;
    public state?: Elements.TextElement;
    public zipCode?: Elements.TextElement;
    public sitemap?: Elements.TaxonomyElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'zip_code') {
                    return 'zipCode';
                }
                return elementName;
            })
        });
    }
}
