
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class FactAboutUsItem extends ContentItem {
    public description?: Elements.RichTextElement;
    public title?: Elements.TextElement;
    public sitemap?: Elements.TaxonomyElement;
    public image?: Elements.AssetsElement;
}
