
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class HeroUnitItem extends ContentItem {
    public sitemap?: Elements.TaxonomyElement;
    public title?: Elements.TextElement;
    public image?: Elements.AssetsElement;
    public marketingMessage?: Elements.RichTextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'marketing_message') {
                    return 'marketingMessage';
                }
                return elementName;
            })
        });
    }
}
