
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class HostedVideoItem extends ContentItem {
    public videoId?: Elements.TextElement;
    public videoHost?: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'video_id') {
                    return 'videoId';
                }
                if (elementName === 'video_host') {
                    return 'videoHost';
                }
                return elementName;
            })
        });
    }
}
