
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.2.0'
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class TweetItem extends ContentItem {
    public tweetLink?: Elements.TextElement;
    public theme?: Elements.MultipleChoiceElement;
    public displayOptions?: Elements.MultipleChoiceElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'tweet_link') {
                    return 'tweetLink';
                }
                if (elementName === 'display_options') {
                    return 'displayOptions';
                }
                return elementName;
            })
        });
    }
}
